// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_epub_data`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Open an EPUB file from path and load all data
Future<EpubBook> openEpub({required String path}) =>
    RustLib.instance.api.crateApiEpubOpenEpub(path: path);

/// Open an EPUB from raw bytes and load all data
Future<EpubBook> openEpubBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiEpubOpenEpubBytes(bytes: bytes);

/// Read a specific chapter by index
Future<String> readChapter({required EpubBook book, required BigInt index}) =>
    RustLib.instance.api.crateApiEpubReadChapter(book: book, index: index);

/// Get the number of chapters in the book
BigInt getChapterCount({required EpubBook book}) =>
    RustLib.instance.api.crateApiEpubGetChapterCount(book: book);

/// Get metadata from the book
EpubMetadata getMetadata({required EpubBook book}) =>
    RustLib.instance.api.crateApiEpubGetMetadata(book: book);

/// Get table of contents entries
List<TocEntry> getToc({required EpubBook book}) =>
    RustLib.instance.api.crateApiEpubGetToc(book: book);

/// Get chapter info list
List<ChapterInfo> getChapters({required EpubBook book}) =>
    RustLib.instance.api.crateApiEpubGetChapters(book: book);

/// Get cover image bytes
Uint8List? getCover({required EpubBook book}) =>
    RustLib.instance.api.crateApiEpubGetCover(book: book);

/// A chapter from the EPUB spine
class ChapterInfo {
  final BigInt index;
  final String id;
  final String href;
  final String mediaType;

  const ChapterInfo({
    required this.index,
    required this.id,
    required this.href,
    required this.mediaType,
  });

  @override
  int get hashCode =>
      index.hashCode ^ id.hashCode ^ href.hashCode ^ mediaType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          id == other.id &&
          href == other.href &&
          mediaType == other.mediaType;
}

/// EPUB book data - we load everything upfront to avoid lifetime issues with FFI
class EpubBook {
  final EpubMetadata metadata;
  final List<ChapterInfo> chapters;
  final List<TocEntry> toc;
  final Uint8List? coverImage;
  final List<String> chapterContents;

  const EpubBook({
    required this.metadata,
    required this.chapters,
    required this.toc,
    this.coverImage,
    required this.chapterContents,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^
      chapters.hashCode ^
      toc.hashCode ^
      coverImage.hashCode ^
      chapterContents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubBook &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          chapters == other.chapters &&
          toc == other.toc &&
          coverImage == other.coverImage &&
          chapterContents == other.chapterContents;
}

/// Error type for EPUB operations
class EpubError implements FrbException {
  final String message;

  const EpubError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Metadata extracted from an EPUB file
class EpubMetadata {
  final String? title;
  final String? creator;
  final String? language;
  final String? identifier;
  final String? publisher;
  final String? description;

  const EpubMetadata({
    this.title,
    this.creator,
    this.language,
    this.identifier,
    this.publisher,
    this.description,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      creator.hashCode ^
      language.hashCode ^
      identifier.hashCode ^
      publisher.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          creator == other.creator &&
          language == other.language &&
          identifier == other.identifier &&
          publisher == other.publisher &&
          description == other.description;
}

/// A single entry in the table of contents
class TocEntry {
  final String title;
  final String href;

  const TocEntry({required this.title, required this.href});

  @override
  int get hashCode => title.hashCode ^ href.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TocEntry &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          href == other.href;
}
