// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_render_model`, `map_runtime_error`, `to_i32`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Open an EPUB file from path and parse runtime reader sections.
Future<ParsedEpubBook> openEpub({required String path}) =>
    RustLib.instance.api.crateApiEpubOpenEpub(path: path);

/// Lazily read a book resource from the EPUB archive.
Future<Uint8List?> readBookResourceBytes({
  required String path,
  required ResourceRef resource,
}) => RustLib.instance.api.crateApiEpubReadBookResourceBytes(
  path: path,
  resource: resource,
);

/// Error type for EPUB operations.
class EpubError implements FrbException {
  final String message;

  const EpubError({required this.message});

  @override
  int get hashCode => message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubError &&
          runtimeType == other.runtimeType &&
          message == other.message;
}

/// Metadata extracted from an EPUB file.
class EpubMetadata {
  final String? title;
  final String? creator;
  final String? language;
  final String? identifier;
  final String? publisher;
  final String? description;

  const EpubMetadata({
    this.title,
    this.creator,
    this.language,
    this.identifier,
    this.publisher,
    this.description,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      creator.hashCode ^
      language.hashCode ^
      identifier.hashCode ^
      publisher.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubMetadata &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          creator == other.creator &&
          language == other.language &&
          identifier == other.identifier &&
          publisher == other.publisher &&
          description == other.description;
}

class ImageLength {
  final int valueMilli;
  final ImageLengthUnit unit;

  const ImageLength({required this.valueMilli, required this.unit});

  @override
  int get hashCode => valueMilli.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageLength &&
          runtimeType == other.runtimeType &&
          valueMilli == other.valueMilli &&
          unit == other.unit;
}

enum ImageLengthUnit { percent, px, em, rem, auto }

class ImagePresentation {
  final ImageLength? width;
  final ImageLength? height;
  final ImageLength? maxWidth;
  final ImageLength? maxHeight;

  const ImagePresentation({
    this.width,
    this.height,
    this.maxWidth,
    this.maxHeight,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ maxWidth.hashCode ^ maxHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImagePresentation &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight;
}

class LinkTarget {
  final LinkTargetKind kind;
  final String href;
  final String? sectionId;
  final int? sectionIndex;
  final String? fragment;

  const LinkTarget({
    required this.kind,
    required this.href,
    this.sectionId,
    this.sectionIndex,
    this.fragment,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      href.hashCode ^
      sectionId.hashCode ^
      sectionIndex.hashCode ^
      fragment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkTarget &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          href == other.href &&
          sectionId == other.sectionId &&
          sectionIndex == other.sectionIndex &&
          fragment == other.fragment;
}

enum LinkTargetKind { internal, external_, unresolved }

class ListItem {
  final List<ReaderBlock> blocks;
  final SourceMap source;

  const ListItem({required this.blocks, required this.source});

  @override
  int get hashCode => blocks.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListItem &&
          runtimeType == other.runtimeType &&
          blocks == other.blocks &&
          source == other.source;
}

/// Fully parsed runtime book data.
class ParsedEpubBook {
  final EpubMetadata metadata;
  final Uint8List? coverImage;
  final List<Section> sections;

  const ParsedEpubBook({
    required this.metadata,
    this.coverImage,
    required this.sections,
  });

  @override
  int get hashCode =>
      metadata.hashCode ^ coverImage.hashCode ^ sections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedEpubBook &&
          runtimeType == other.runtimeType &&
          metadata == other.metadata &&
          coverImage == other.coverImage &&
          sections == other.sections;
}

class ReaderBlock {
  final ReaderBlockKind kind;
  final int level;
  final bool ordered;
  final List<ReaderInline> inlines;
  final List<ReaderBlock> blocks;
  final List<ListItem> items;
  final ResourceRef? resource;
  final String? alt;
  final String? caption;
  final ImagePresentation? presentation;
  final List<TableRow> rows;
  final String? codeText;
  final SourceMap source;

  const ReaderBlock({
    required this.kind,
    required this.level,
    required this.ordered,
    required this.inlines,
    required this.blocks,
    required this.items,
    this.resource,
    this.alt,
    this.caption,
    this.presentation,
    required this.rows,
    this.codeText,
    required this.source,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      level.hashCode ^
      ordered.hashCode ^
      inlines.hashCode ^
      blocks.hashCode ^
      items.hashCode ^
      resource.hashCode ^
      alt.hashCode ^
      caption.hashCode ^
      presentation.hashCode ^
      rows.hashCode ^
      codeText.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderBlock &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          level == other.level &&
          ordered == other.ordered &&
          inlines == other.inlines &&
          blocks == other.blocks &&
          items == other.items &&
          resource == other.resource &&
          alt == other.alt &&
          caption == other.caption &&
          presentation == other.presentation &&
          rows == other.rows &&
          codeText == other.codeText &&
          source == other.source;
}

enum ReaderBlockKind {
  paragraph,
  heading,
  blockQuote,
  list,
  listItem,
  image,
  table,
  horizontalRule,
  code,
}

class ReaderDocument {
  final String chapterHref;
  final List<ReaderBlock> blocks;

  const ReaderDocument({required this.chapterHref, required this.blocks});

  @override
  int get hashCode => chapterHref.hashCode ^ blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderDocument &&
          runtimeType == other.runtimeType &&
          chapterHref == other.chapterHref &&
          blocks == other.blocks;
}

class ReaderInline {
  final ReaderInlineKind kind;
  final String? text;
  final LinkTarget? target;
  final ResourceRef? resource;
  final String? alt;
  final ImagePresentation? presentation;
  final List<SpanStyleHint> styleHints;
  final List<ReaderInline> children;
  final SourceMap source;

  const ReaderInline({
    required this.kind,
    this.text,
    this.target,
    this.resource,
    this.alt,
    this.presentation,
    required this.styleHints,
    required this.children,
    required this.source,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      target.hashCode ^
      resource.hashCode ^
      alt.hashCode ^
      presentation.hashCode ^
      styleHints.hashCode ^
      children.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderInline &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          target == other.target &&
          resource == other.resource &&
          alt == other.alt &&
          presentation == other.presentation &&
          styleHints == other.styleHints &&
          children == other.children &&
          source == other.source;
}

enum ReaderInlineKind { text, span, link, image, lineBreak }

enum ResourceKind { image, stylesheet, cover, other }

class ResourceRef {
  final String href;
  final String? mediaType;
  final ResourceKind kind;

  const ResourceRef({required this.href, this.mediaType, required this.kind});

  @override
  int get hashCode => href.hashCode ^ mediaType.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResourceRef &&
          runtimeType == other.runtimeType &&
          href == other.href &&
          mediaType == other.mediaType &&
          kind == other.kind;
}

class Section {
  final String id;
  final String title;
  final String startHref;
  final String? startFragment;
  final String? endHref;
  final String? endFragment;
  final int spineStart;
  final int spineEnd;
  final List<String> anchors;
  final ReaderDocument document;

  const Section({
    required this.id,
    required this.title,
    required this.startHref,
    this.startFragment,
    this.endHref,
    this.endFragment,
    required this.spineStart,
    required this.spineEnd,
    required this.anchors,
    required this.document,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      startHref.hashCode ^
      startFragment.hashCode ^
      endHref.hashCode ^
      endFragment.hashCode ^
      spineStart.hashCode ^
      spineEnd.hashCode ^
      anchors.hashCode ^
      document.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Section &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          startHref == other.startHref &&
          startFragment == other.startFragment &&
          endHref == other.endHref &&
          endFragment == other.endFragment &&
          spineStart == other.spineStart &&
          spineEnd == other.spineEnd &&
          anchors == other.anchors &&
          document == other.document;
}

class SourceMap {
  final int spineIndex;
  final String href;
  final String? fragment;
  final Int32List nodePath;

  const SourceMap({
    required this.spineIndex,
    required this.href,
    this.fragment,
    required this.nodePath,
  });

  @override
  int get hashCode =>
      spineIndex.hashCode ^
      href.hashCode ^
      fragment.hashCode ^
      nodePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceMap &&
          runtimeType == other.runtimeType &&
          spineIndex == other.spineIndex &&
          href == other.href &&
          fragment == other.fragment &&
          nodePath == other.nodePath;
}

enum SpanStyleHint { italic, bold, underline, superscript, subscript, code }

class TableCell {
  final bool isHeader;
  final List<ReaderInline> inlines;
  final SourceMap source;

  const TableCell({
    required this.isHeader,
    required this.inlines,
    required this.source,
  });

  @override
  int get hashCode => isHeader.hashCode ^ inlines.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableCell &&
          runtimeType == other.runtimeType &&
          isHeader == other.isHeader &&
          inlines == other.inlines &&
          source == other.source;
}

class TableRow {
  final List<TableCell> cells;
  final SourceMap source;

  const TableRow({required this.cells, required this.source});

  @override
  int get hashCode => cells.hashCode ^ source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableRow &&
          runtimeType == other.runtimeType &&
          cells == other.cells &&
          source == other.source;
}
