// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/epub.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EpubError dco_decode_epub_error(dynamic raw);

  @protected
  EpubMetadata dco_decode_epub_metadata(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  ListItem dco_decode_list_item(dynamic raw);

  @protected
  List<ListItem> dco_decode_list_list_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ReaderBlock> dco_decode_list_reader_block(dynamic raw);

  @protected
  List<ReaderInline> dco_decode_list_reader_inline(dynamic raw);

  @protected
  List<Section> dco_decode_list_section(dynamic raw);

  @protected
  List<SpanStyleHint> dco_decode_list_span_style_hint(dynamic raw);

  @protected
  List<TableCell> dco_decode_list_table_cell(dynamic raw);

  @protected
  List<TableRow> dco_decode_list_table_row(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ParsedEpubBook dco_decode_parsed_epub_book(dynamic raw);

  @protected
  ReaderBlock dco_decode_reader_block(dynamic raw);

  @protected
  ReaderBlockKind dco_decode_reader_block_kind(dynamic raw);

  @protected
  ReaderDocument dco_decode_reader_document(dynamic raw);

  @protected
  ReaderInline dco_decode_reader_inline(dynamic raw);

  @protected
  ReaderInlineKind dco_decode_reader_inline_kind(dynamic raw);

  @protected
  Section dco_decode_section(dynamic raw);

  @protected
  SpanStyleHint dco_decode_span_style_hint(dynamic raw);

  @protected
  TableCell dco_decode_table_cell(dynamic raw);

  @protected
  TableRow dco_decode_table_row(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EpubError sse_decode_epub_error(SseDeserializer deserializer);

  @protected
  EpubMetadata sse_decode_epub_metadata(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  ListItem sse_decode_list_item(SseDeserializer deserializer);

  @protected
  List<ListItem> sse_decode_list_list_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ReaderBlock> sse_decode_list_reader_block(SseDeserializer deserializer);

  @protected
  List<ReaderInline> sse_decode_list_reader_inline(
    SseDeserializer deserializer,
  );

  @protected
  List<Section> sse_decode_list_section(SseDeserializer deserializer);

  @protected
  List<SpanStyleHint> sse_decode_list_span_style_hint(
    SseDeserializer deserializer,
  );

  @protected
  List<TableCell> sse_decode_list_table_cell(SseDeserializer deserializer);

  @protected
  List<TableRow> sse_decode_list_table_row(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ParsedEpubBook sse_decode_parsed_epub_book(SseDeserializer deserializer);

  @protected
  ReaderBlock sse_decode_reader_block(SseDeserializer deserializer);

  @protected
  ReaderBlockKind sse_decode_reader_block_kind(SseDeserializer deserializer);

  @protected
  ReaderDocument sse_decode_reader_document(SseDeserializer deserializer);

  @protected
  ReaderInline sse_decode_reader_inline(SseDeserializer deserializer);

  @protected
  ReaderInlineKind sse_decode_reader_inline_kind(SseDeserializer deserializer);

  @protected
  Section sse_decode_section(SseDeserializer deserializer);

  @protected
  SpanStyleHint sse_decode_span_style_hint(SseDeserializer deserializer);

  @protected
  TableCell sse_decode_table_cell(SseDeserializer deserializer);

  @protected
  TableRow sse_decode_table_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_epub_error(EpubError self, SseSerializer serializer);

  @protected
  void sse_encode_epub_metadata(EpubMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_item(ListItem self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_item(List<ListItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reader_block(
    List<ReaderBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_reader_inline(
    List<ReaderInline> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_section(List<Section> self, SseSerializer serializer);

  @protected
  void sse_encode_list_span_style_hint(
    List<SpanStyleHint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_cell(
    List<TableCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_row(List<TableRow> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_parsed_epub_book(
    ParsedEpubBook self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reader_block(ReaderBlock self, SseSerializer serializer);

  @protected
  void sse_encode_reader_block_kind(
    ReaderBlockKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reader_document(
    ReaderDocument self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reader_inline(ReaderInline self, SseSerializer serializer);

  @protected
  void sse_encode_reader_inline_kind(
    ReaderInlineKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_section(Section self, SseSerializer serializer);

  @protected
  void sse_encode_span_style_hint(SpanStyleHint self, SseSerializer serializer);

  @protected
  void sse_encode_table_cell(TableCell self, SseSerializer serializer);

  @protected
  void sse_encode_table_row(TableRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
