// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/epub.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
    await api.crateApiEpubInitEpubApi();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 356072837;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_audiobookify_app5',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiEpubInitEpubApi();

  Future<ParsedEpubBook> crateApiEpubOpenEpub({required String path});

  Future<Uint8List?> crateApiEpubReadBookResourceBytes({
    required String path,
    required ResourceRef resource,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiEpubInitEpubApi() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEpubInitEpubApiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEpubInitEpubApiConstMeta =>
      const TaskConstMeta(debugName: "init_epub_api", argNames: []);

  @override
  Future<ParsedEpubBook> crateApiEpubOpenEpub({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_epub_book,
          decodeErrorData: sse_decode_epub_error,
        ),
        constMeta: kCrateApiEpubOpenEpubConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEpubOpenEpubConstMeta =>
      const TaskConstMeta(debugName: "open_epub", argNames: ["path"]);

  @override
  Future<Uint8List?> crateApiEpubReadBookResourceBytes({
    required String path,
    required ResourceRef resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_resource_ref(resource, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_epub_error,
        ),
        constMeta: kCrateApiEpubReadBookResourceBytesConstMeta,
        argValues: [path, resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEpubReadBookResourceBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_book_resource_bytes",
        argNames: ["path", "resource"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageLength dco_decode_box_autoadd_image_length(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_length(raw);
  }

  @protected
  ImagePresentation dco_decode_box_autoadd_image_presentation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_presentation(raw);
  }

  @protected
  LinkTarget dco_decode_box_autoadd_link_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_link_target(raw);
  }

  @protected
  ResourceRef dco_decode_box_autoadd_resource_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_resource_ref(raw);
  }

  @protected
  EpubError dco_decode_epub_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return EpubError(message: dco_decode_String(arr[0]));
  }

  @protected
  EpubMetadata dco_decode_epub_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return EpubMetadata(
      title: dco_decode_opt_String(arr[0]),
      creator: dco_decode_opt_String(arr[1]),
      language: dco_decode_opt_String(arr[2]),
      identifier: dco_decode_opt_String(arr[3]),
      publisher: dco_decode_opt_String(arr[4]),
      description: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImageLength dco_decode_image_length(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ImageLength(
      valueMilli: dco_decode_i_32(arr[0]),
      unit: dco_decode_image_length_unit(arr[1]),
    );
  }

  @protected
  ImageLengthUnit dco_decode_image_length_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ImageLengthUnit.values[raw as int];
  }

  @protected
  ImagePresentation dco_decode_image_presentation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImagePresentation(
      width: dco_decode_opt_box_autoadd_image_length(arr[0]),
      height: dco_decode_opt_box_autoadd_image_length(arr[1]),
      maxWidth: dco_decode_opt_box_autoadd_image_length(arr[2]),
      maxHeight: dco_decode_opt_box_autoadd_image_length(arr[3]),
    );
  }

  @protected
  LinkTarget dco_decode_link_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LinkTarget(
      kind: dco_decode_link_target_kind(arr[0]),
      href: dco_decode_String(arr[1]),
      sectionId: dco_decode_opt_String(arr[2]),
      sectionIndex: dco_decode_opt_box_autoadd_i_32(arr[3]),
      fragment: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  LinkTargetKind dco_decode_link_target_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LinkTargetKind.values[raw as int];
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  ListItem dco_decode_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ListItem(
      blocks: dco_decode_list_reader_block(arr[0]),
      source: dco_decode_source_map(arr[1]),
    );
  }

  @protected
  List<ListItem> dco_decode_list_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_item).toList();
  }

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ReaderBlock> dco_decode_list_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_block).toList();
  }

  @protected
  List<ReaderInline> dco_decode_list_reader_inline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_reader_inline).toList();
  }

  @protected
  List<Section> dco_decode_list_section(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_section).toList();
  }

  @protected
  List<SpanStyleHint> dco_decode_list_span_style_hint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_span_style_hint).toList();
  }

  @protected
  List<TableCell> dco_decode_list_table_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_table_cell).toList();
  }

  @protected
  List<TableRow> dco_decode_list_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_table_row).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  ImageLength? dco_decode_opt_box_autoadd_image_length(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_image_length(raw);
  }

  @protected
  ImagePresentation? dco_decode_opt_box_autoadd_image_presentation(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_image_presentation(raw);
  }

  @protected
  LinkTarget? dco_decode_opt_box_autoadd_link_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_link_target(raw);
  }

  @protected
  ResourceRef? dco_decode_opt_box_autoadd_resource_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_resource_ref(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ParsedEpubBook dco_decode_parsed_epub_book(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ParsedEpubBook(
      metadata: dco_decode_epub_metadata(arr[0]),
      coverImage: dco_decode_opt_list_prim_u_8_strict(arr[1]),
      sections: dco_decode_list_section(arr[2]),
    );
  }

  @protected
  ReaderBlock dco_decode_reader_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ReaderBlock(
      kind: dco_decode_reader_block_kind(arr[0]),
      level: dco_decode_i_32(arr[1]),
      ordered: dco_decode_bool(arr[2]),
      inlines: dco_decode_list_reader_inline(arr[3]),
      blocks: dco_decode_list_reader_block(arr[4]),
      items: dco_decode_list_list_item(arr[5]),
      resource: dco_decode_opt_box_autoadd_resource_ref(arr[6]),
      alt: dco_decode_opt_String(arr[7]),
      caption: dco_decode_opt_String(arr[8]),
      presentation: dco_decode_opt_box_autoadd_image_presentation(arr[9]),
      rows: dco_decode_list_table_row(arr[10]),
      codeText: dco_decode_opt_String(arr[11]),
      source: dco_decode_source_map(arr[12]),
    );
  }

  @protected
  ReaderBlockKind dco_decode_reader_block_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReaderBlockKind.values[raw as int];
  }

  @protected
  ReaderDocument dco_decode_reader_document(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ReaderDocument(
      chapterHref: dco_decode_String(arr[0]),
      blocks: dco_decode_list_reader_block(arr[1]),
    );
  }

  @protected
  ReaderInline dco_decode_reader_inline(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ReaderInline(
      kind: dco_decode_reader_inline_kind(arr[0]),
      text: dco_decode_opt_String(arr[1]),
      target: dco_decode_opt_box_autoadd_link_target(arr[2]),
      resource: dco_decode_opt_box_autoadd_resource_ref(arr[3]),
      alt: dco_decode_opt_String(arr[4]),
      presentation: dco_decode_opt_box_autoadd_image_presentation(arr[5]),
      styleHints: dco_decode_list_span_style_hint(arr[6]),
      children: dco_decode_list_reader_inline(arr[7]),
      source: dco_decode_source_map(arr[8]),
    );
  }

  @protected
  ReaderInlineKind dco_decode_reader_inline_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReaderInlineKind.values[raw as int];
  }

  @protected
  ResourceKind dco_decode_resource_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ResourceKind.values[raw as int];
  }

  @protected
  ResourceRef dco_decode_resource_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ResourceRef(
      href: dco_decode_String(arr[0]),
      mediaType: dco_decode_opt_String(arr[1]),
      kind: dco_decode_resource_kind(arr[2]),
    );
  }

  @protected
  Section dco_decode_section(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Section(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      startHref: dco_decode_String(arr[2]),
      startFragment: dco_decode_opt_String(arr[3]),
      endHref: dco_decode_opt_String(arr[4]),
      endFragment: dco_decode_opt_String(arr[5]),
      spineStart: dco_decode_i_32(arr[6]),
      spineEnd: dco_decode_i_32(arr[7]),
      anchors: dco_decode_list_String(arr[8]),
      document: dco_decode_reader_document(arr[9]),
    );
  }

  @protected
  SourceMap dco_decode_source_map(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SourceMap(
      spineIndex: dco_decode_i_32(arr[0]),
      href: dco_decode_String(arr[1]),
      fragment: dco_decode_opt_String(arr[2]),
      nodePath: dco_decode_list_prim_i_32_strict(arr[3]),
    );
  }

  @protected
  SpanStyleHint dco_decode_span_style_hint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpanStyleHint.values[raw as int];
  }

  @protected
  TableCell dco_decode_table_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TableCell(
      isHeader: dco_decode_bool(arr[0]),
      inlines: dco_decode_list_reader_inline(arr[1]),
      source: dco_decode_source_map(arr[2]),
    );
  }

  @protected
  TableRow dco_decode_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TableRow(
      cells: dco_decode_list_table_cell(arr[0]),
      source: dco_decode_source_map(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  ImageLength sse_decode_box_autoadd_image_length(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_length(deserializer));
  }

  @protected
  ImagePresentation sse_decode_box_autoadd_image_presentation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_presentation(deserializer));
  }

  @protected
  LinkTarget sse_decode_box_autoadd_link_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_link_target(deserializer));
  }

  @protected
  ResourceRef sse_decode_box_autoadd_resource_ref(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_resource_ref(deserializer));
  }

  @protected
  EpubError sse_decode_epub_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_message = sse_decode_String(deserializer);
    return EpubError(message: var_message);
  }

  @protected
  EpubMetadata sse_decode_epub_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_creator = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_identifier = sse_decode_opt_String(deserializer);
    var var_publisher = sse_decode_opt_String(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return EpubMetadata(
      title: var_title,
      creator: var_creator,
      language: var_language,
      identifier: var_identifier,
      publisher: var_publisher,
      description: var_description,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImageLength sse_decode_image_length(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_valueMilli = sse_decode_i_32(deserializer);
    var var_unit = sse_decode_image_length_unit(deserializer);
    return ImageLength(valueMilli: var_valueMilli, unit: var_unit);
  }

  @protected
  ImageLengthUnit sse_decode_image_length_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ImageLengthUnit.values[inner];
  }

  @protected
  ImagePresentation sse_decode_image_presentation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_opt_box_autoadd_image_length(deserializer);
    var var_height = sse_decode_opt_box_autoadd_image_length(deserializer);
    var var_maxWidth = sse_decode_opt_box_autoadd_image_length(deserializer);
    var var_maxHeight = sse_decode_opt_box_autoadd_image_length(deserializer);
    return ImagePresentation(
      width: var_width,
      height: var_height,
      maxWidth: var_maxWidth,
      maxHeight: var_maxHeight,
    );
  }

  @protected
  LinkTarget sse_decode_link_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_link_target_kind(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_sectionId = sse_decode_opt_String(deserializer);
    var var_sectionIndex = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_fragment = sse_decode_opt_String(deserializer);
    return LinkTarget(
      kind: var_kind,
      href: var_href,
      sectionId: var_sectionId,
      sectionIndex: var_sectionIndex,
      fragment: var_fragment,
    );
  }

  @protected
  LinkTargetKind sse_decode_link_target_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return LinkTargetKind.values[inner];
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  ListItem sse_decode_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blocks = sse_decode_list_reader_block(deserializer);
    var var_source = sse_decode_source_map(deserializer);
    return ListItem(blocks: var_blocks, source: var_source);
  }

  @protected
  List<ListItem> sse_decode_list_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ReaderBlock> sse_decode_list_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReaderBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<ReaderInline> sse_decode_list_reader_inline(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ReaderInline>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_reader_inline(deserializer));
    }
    return ans_;
  }

  @protected
  List<Section> sse_decode_list_section(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Section>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_section(deserializer));
    }
    return ans_;
  }

  @protected
  List<SpanStyleHint> sse_decode_list_span_style_hint(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpanStyleHint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_span_style_hint(deserializer));
    }
    return ans_;
  }

  @protected
  List<TableCell> sse_decode_list_table_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TableCell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_table_cell(deserializer));
    }
    return ans_;
  }

  @protected
  List<TableRow> sse_decode_list_table_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TableRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_table_row(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ImageLength? sse_decode_opt_box_autoadd_image_length(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_image_length(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ImagePresentation? sse_decode_opt_box_autoadd_image_presentation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_image_presentation(deserializer));
    } else {
      return null;
    }
  }

  @protected
  LinkTarget? sse_decode_opt_box_autoadd_link_target(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_link_target(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ResourceRef? sse_decode_opt_box_autoadd_resource_ref(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_resource_ref(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParsedEpubBook sse_decode_parsed_epub_book(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metadata = sse_decode_epub_metadata(deserializer);
    var var_coverImage = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_sections = sse_decode_list_section(deserializer);
    return ParsedEpubBook(
      metadata: var_metadata,
      coverImage: var_coverImage,
      sections: var_sections,
    );
  }

  @protected
  ReaderBlock sse_decode_reader_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_reader_block_kind(deserializer);
    var var_level = sse_decode_i_32(deserializer);
    var var_ordered = sse_decode_bool(deserializer);
    var var_inlines = sse_decode_list_reader_inline(deserializer);
    var var_blocks = sse_decode_list_reader_block(deserializer);
    var var_items = sse_decode_list_list_item(deserializer);
    var var_resource = sse_decode_opt_box_autoadd_resource_ref(deserializer);
    var var_alt = sse_decode_opt_String(deserializer);
    var var_caption = sse_decode_opt_String(deserializer);
    var var_presentation = sse_decode_opt_box_autoadd_image_presentation(
      deserializer,
    );
    var var_rows = sse_decode_list_table_row(deserializer);
    var var_codeText = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_source_map(deserializer);
    return ReaderBlock(
      kind: var_kind,
      level: var_level,
      ordered: var_ordered,
      inlines: var_inlines,
      blocks: var_blocks,
      items: var_items,
      resource: var_resource,
      alt: var_alt,
      caption: var_caption,
      presentation: var_presentation,
      rows: var_rows,
      codeText: var_codeText,
      source: var_source,
    );
  }

  @protected
  ReaderBlockKind sse_decode_reader_block_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReaderBlockKind.values[inner];
  }

  @protected
  ReaderDocument sse_decode_reader_document(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterHref = sse_decode_String(deserializer);
    var var_blocks = sse_decode_list_reader_block(deserializer);
    return ReaderDocument(chapterHref: var_chapterHref, blocks: var_blocks);
  }

  @protected
  ReaderInline sse_decode_reader_inline(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_reader_inline_kind(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_target = sse_decode_opt_box_autoadd_link_target(deserializer);
    var var_resource = sse_decode_opt_box_autoadd_resource_ref(deserializer);
    var var_alt = sse_decode_opt_String(deserializer);
    var var_presentation = sse_decode_opt_box_autoadd_image_presentation(
      deserializer,
    );
    var var_styleHints = sse_decode_list_span_style_hint(deserializer);
    var var_children = sse_decode_list_reader_inline(deserializer);
    var var_source = sse_decode_source_map(deserializer);
    return ReaderInline(
      kind: var_kind,
      text: var_text,
      target: var_target,
      resource: var_resource,
      alt: var_alt,
      presentation: var_presentation,
      styleHints: var_styleHints,
      children: var_children,
      source: var_source,
    );
  }

  @protected
  ReaderInlineKind sse_decode_reader_inline_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ReaderInlineKind.values[inner];
  }

  @protected
  ResourceKind sse_decode_resource_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ResourceKind.values[inner];
  }

  @protected
  ResourceRef sse_decode_resource_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_href = sse_decode_String(deserializer);
    var var_mediaType = sse_decode_opt_String(deserializer);
    var var_kind = sse_decode_resource_kind(deserializer);
    return ResourceRef(
      href: var_href,
      mediaType: var_mediaType,
      kind: var_kind,
    );
  }

  @protected
  Section sse_decode_section(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_startHref = sse_decode_String(deserializer);
    var var_startFragment = sse_decode_opt_String(deserializer);
    var var_endHref = sse_decode_opt_String(deserializer);
    var var_endFragment = sse_decode_opt_String(deserializer);
    var var_spineStart = sse_decode_i_32(deserializer);
    var var_spineEnd = sse_decode_i_32(deserializer);
    var var_anchors = sse_decode_list_String(deserializer);
    var var_document = sse_decode_reader_document(deserializer);
    return Section(
      id: var_id,
      title: var_title,
      startHref: var_startHref,
      startFragment: var_startFragment,
      endHref: var_endHref,
      endFragment: var_endFragment,
      spineStart: var_spineStart,
      spineEnd: var_spineEnd,
      anchors: var_anchors,
      document: var_document,
    );
  }

  @protected
  SourceMap sse_decode_source_map(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spineIndex = sse_decode_i_32(deserializer);
    var var_href = sse_decode_String(deserializer);
    var var_fragment = sse_decode_opt_String(deserializer);
    var var_nodePath = sse_decode_list_prim_i_32_strict(deserializer);
    return SourceMap(
      spineIndex: var_spineIndex,
      href: var_href,
      fragment: var_fragment,
      nodePath: var_nodePath,
    );
  }

  @protected
  SpanStyleHint sse_decode_span_style_hint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SpanStyleHint.values[inner];
  }

  @protected
  TableCell sse_decode_table_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isHeader = sse_decode_bool(deserializer);
    var var_inlines = sse_decode_list_reader_inline(deserializer);
    var var_source = sse_decode_source_map(deserializer);
    return TableCell(
      isHeader: var_isHeader,
      inlines: var_inlines,
      source: var_source,
    );
  }

  @protected
  TableRow sse_decode_table_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cells = sse_decode_list_table_cell(deserializer);
    var var_source = sse_decode_source_map(deserializer);
    return TableRow(cells: var_cells, source: var_source);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_length(
    ImageLength self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_length(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_presentation(
    ImagePresentation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_presentation(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_link_target(
    LinkTarget self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_link_target(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_resource_ref(
    ResourceRef self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_resource_ref(self, serializer);
  }

  @protected
  void sse_encode_epub_error(EpubError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_epub_metadata(EpubMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.creator, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.identifier, serializer);
    sse_encode_opt_String(self.publisher, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_image_length(ImageLength self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.valueMilli, serializer);
    sse_encode_image_length_unit(self.unit, serializer);
  }

  @protected
  void sse_encode_image_length_unit(
    ImageLengthUnit self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_image_presentation(
    ImagePresentation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_image_length(self.width, serializer);
    sse_encode_opt_box_autoadd_image_length(self.height, serializer);
    sse_encode_opt_box_autoadd_image_length(self.maxWidth, serializer);
    sse_encode_opt_box_autoadd_image_length(self.maxHeight, serializer);
  }

  @protected
  void sse_encode_link_target(LinkTarget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_link_target_kind(self.kind, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_opt_String(self.sectionId, serializer);
    sse_encode_opt_box_autoadd_i_32(self.sectionIndex, serializer);
    sse_encode_opt_String(self.fragment, serializer);
  }

  @protected
  void sse_encode_link_target_kind(
    LinkTargetKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_item(ListItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_reader_block(self.blocks, serializer);
    sse_encode_source_map(self.source, serializer);
  }

  @protected
  void sse_encode_list_list_item(
    List<ListItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_reader_block(
    List<ReaderBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_reader_inline(
    List<ReaderInline> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_reader_inline(item, serializer);
    }
  }

  @protected
  void sse_encode_list_section(List<Section> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_section(item, serializer);
    }
  }

  @protected
  void sse_encode_list_span_style_hint(
    List<SpanStyleHint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_span_style_hint(item, serializer);
    }
  }

  @protected
  void sse_encode_list_table_cell(
    List<TableCell> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_table_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_list_table_row(
    List<TableRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_table_row(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_image_length(
    ImageLength? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_image_length(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_image_presentation(
    ImagePresentation? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_image_presentation(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_link_target(
    LinkTarget? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_link_target(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_resource_ref(
    ResourceRef? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_resource_ref(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_parsed_epub_book(
    ParsedEpubBook self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_epub_metadata(self.metadata, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.coverImage, serializer);
    sse_encode_list_section(self.sections, serializer);
  }

  @protected
  void sse_encode_reader_block(ReaderBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_reader_block_kind(self.kind, serializer);
    sse_encode_i_32(self.level, serializer);
    sse_encode_bool(self.ordered, serializer);
    sse_encode_list_reader_inline(self.inlines, serializer);
    sse_encode_list_reader_block(self.blocks, serializer);
    sse_encode_list_list_item(self.items, serializer);
    sse_encode_opt_box_autoadd_resource_ref(self.resource, serializer);
    sse_encode_opt_String(self.alt, serializer);
    sse_encode_opt_String(self.caption, serializer);
    sse_encode_opt_box_autoadd_image_presentation(
      self.presentation,
      serializer,
    );
    sse_encode_list_table_row(self.rows, serializer);
    sse_encode_opt_String(self.codeText, serializer);
    sse_encode_source_map(self.source, serializer);
  }

  @protected
  void sse_encode_reader_block_kind(
    ReaderBlockKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_reader_document(
    ReaderDocument self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chapterHref, serializer);
    sse_encode_list_reader_block(self.blocks, serializer);
  }

  @protected
  void sse_encode_reader_inline(ReaderInline self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_reader_inline_kind(self.kind, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_box_autoadd_link_target(self.target, serializer);
    sse_encode_opt_box_autoadd_resource_ref(self.resource, serializer);
    sse_encode_opt_String(self.alt, serializer);
    sse_encode_opt_box_autoadd_image_presentation(
      self.presentation,
      serializer,
    );
    sse_encode_list_span_style_hint(self.styleHints, serializer);
    sse_encode_list_reader_inline(self.children, serializer);
    sse_encode_source_map(self.source, serializer);
  }

  @protected
  void sse_encode_reader_inline_kind(
    ReaderInlineKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_resource_kind(ResourceKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_resource_ref(ResourceRef self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.href, serializer);
    sse_encode_opt_String(self.mediaType, serializer);
    sse_encode_resource_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_section(Section self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.startHref, serializer);
    sse_encode_opt_String(self.startFragment, serializer);
    sse_encode_opt_String(self.endHref, serializer);
    sse_encode_opt_String(self.endFragment, serializer);
    sse_encode_i_32(self.spineStart, serializer);
    sse_encode_i_32(self.spineEnd, serializer);
    sse_encode_list_String(self.anchors, serializer);
    sse_encode_reader_document(self.document, serializer);
  }

  @protected
  void sse_encode_source_map(SourceMap self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.spineIndex, serializer);
    sse_encode_String(self.href, serializer);
    sse_encode_opt_String(self.fragment, serializer);
    sse_encode_list_prim_i_32_strict(self.nodePath, serializer);
  }

  @protected
  void sse_encode_span_style_hint(
    SpanStyleHint self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_table_cell(TableCell self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isHeader, serializer);
    sse_encode_list_reader_inline(self.inlines, serializer);
    sse_encode_source_map(self.source, serializer);
  }

  @protected
  void sse_encode_table_row(TableRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_table_cell(self.cells, serializer);
    sse_encode_source_map(self.source, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
