// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 356072837;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__epub__init_epub_api_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_epub_api",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::epub::init_epub_api();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__epub__open_epub_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "open_epub",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::epub::EpubError>((move || {
                    let output_ok = crate::api::epub::open_epub(api_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__epub__read_book_resource_bytes_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "read_book_resource_bytes",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_resource = <crate::api::epub::ResourceRef>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, crate::api::epub::EpubError>((move || {
                    let output_ok =
                        crate::api::epub::read_book_resource_bytes(api_path, api_resource)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::epub::EpubError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::epub::EpubError {
            message: var_message,
        };
    }
}

impl SseDecode for crate::api::epub::EpubMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_creator = <Option<String>>::sse_decode(deserializer);
        let mut var_language = <Option<String>>::sse_decode(deserializer);
        let mut var_identifier = <Option<String>>::sse_decode(deserializer);
        let mut var_publisher = <Option<String>>::sse_decode(deserializer);
        let mut var_description = <Option<String>>::sse_decode(deserializer);
        return crate::api::epub::EpubMetadata {
            title: var_title,
            creator: var_creator,
            language: var_language,
            identifier: var_identifier,
            publisher: var_publisher,
            description: var_description,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::epub::ImageLength {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_valueMilli = <i32>::sse_decode(deserializer);
        let mut var_unit = <crate::api::epub::ImageLengthUnit>::sse_decode(deserializer);
        return crate::api::epub::ImageLength {
            value_milli: var_valueMilli,
            unit: var_unit,
        };
    }
}

impl SseDecode for crate::api::epub::ImageLengthUnit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::ImageLengthUnit::Percent,
            1 => crate::api::epub::ImageLengthUnit::Px,
            2 => crate::api::epub::ImageLengthUnit::Em,
            3 => crate::api::epub::ImageLengthUnit::Rem,
            4 => crate::api::epub::ImageLengthUnit::Auto,
            _ => unreachable!("Invalid variant for ImageLengthUnit: {}", inner),
        };
    }
}

impl SseDecode for crate::api::epub::ImagePresentation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <Option<crate::api::epub::ImageLength>>::sse_decode(deserializer);
        let mut var_height = <Option<crate::api::epub::ImageLength>>::sse_decode(deserializer);
        let mut var_maxWidth = <Option<crate::api::epub::ImageLength>>::sse_decode(deserializer);
        let mut var_maxHeight = <Option<crate::api::epub::ImageLength>>::sse_decode(deserializer);
        return crate::api::epub::ImagePresentation {
            width: var_width,
            height: var_height,
            max_width: var_maxWidth,
            max_height: var_maxHeight,
        };
    }
}

impl SseDecode for crate::api::epub::LinkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::epub::LinkTargetKind>::sse_decode(deserializer);
        let mut var_href = <String>::sse_decode(deserializer);
        let mut var_sectionId = <Option<String>>::sse_decode(deserializer);
        let mut var_sectionIndex = <Option<i32>>::sse_decode(deserializer);
        let mut var_fragment = <Option<String>>::sse_decode(deserializer);
        return crate::api::epub::LinkTarget {
            kind: var_kind,
            href: var_href,
            section_id: var_sectionId,
            section_index: var_sectionIndex,
            fragment: var_fragment,
        };
    }
}

impl SseDecode for crate::api::epub::LinkTargetKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::LinkTargetKind::Internal,
            1 => crate::api::epub::LinkTargetKind::External,
            2 => crate::api::epub::LinkTargetKind::Unresolved,
            _ => unreachable!("Invalid variant for LinkTargetKind: {}", inner),
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::epub::ListItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_blocks = <Vec<crate::api::epub::ReaderBlock>>::sse_decode(deserializer);
        let mut var_source = <crate::api::epub::SourceMap>::sse_decode(deserializer);
        return crate::api::epub::ListItem {
            blocks: var_blocks,
            source: var_source,
        };
    }
}

impl SseDecode for Vec<crate::api::epub::ListItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::ListItem>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<i32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::ReaderBlock> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::ReaderBlock>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::ReaderInline> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::ReaderInline>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::Section> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::Section>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::SpanStyleHint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::SpanStyleHint>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::TableCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::TableCell>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::epub::TableRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::epub::TableRow>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::epub::ImageLength> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::epub::ImageLength>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::epub::ImagePresentation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::epub::ImagePresentation>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::epub::LinkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::epub::LinkTarget>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::epub::ResourceRef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::epub::ResourceRef>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::epub::ParsedEpubBook {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_metadata = <crate::api::epub::EpubMetadata>::sse_decode(deserializer);
        let mut var_coverImage = <Option<Vec<u8>>>::sse_decode(deserializer);
        let mut var_sections = <Vec<crate::api::epub::Section>>::sse_decode(deserializer);
        return crate::api::epub::ParsedEpubBook {
            metadata: var_metadata,
            cover_image: var_coverImage,
            sections: var_sections,
        };
    }
}

impl SseDecode for crate::api::epub::ReaderBlock {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::epub::ReaderBlockKind>::sse_decode(deserializer);
        let mut var_level = <i32>::sse_decode(deserializer);
        let mut var_ordered = <bool>::sse_decode(deserializer);
        let mut var_inlines = <Vec<crate::api::epub::ReaderInline>>::sse_decode(deserializer);
        let mut var_blocks = <Vec<crate::api::epub::ReaderBlock>>::sse_decode(deserializer);
        let mut var_items = <Vec<crate::api::epub::ListItem>>::sse_decode(deserializer);
        let mut var_resource = <Option<crate::api::epub::ResourceRef>>::sse_decode(deserializer);
        let mut var_alt = <Option<String>>::sse_decode(deserializer);
        let mut var_caption = <Option<String>>::sse_decode(deserializer);
        let mut var_presentation =
            <Option<crate::api::epub::ImagePresentation>>::sse_decode(deserializer);
        let mut var_rows = <Vec<crate::api::epub::TableRow>>::sse_decode(deserializer);
        let mut var_codeText = <Option<String>>::sse_decode(deserializer);
        let mut var_source = <crate::api::epub::SourceMap>::sse_decode(deserializer);
        return crate::api::epub::ReaderBlock {
            kind: var_kind,
            level: var_level,
            ordered: var_ordered,
            inlines: var_inlines,
            blocks: var_blocks,
            items: var_items,
            resource: var_resource,
            alt: var_alt,
            caption: var_caption,
            presentation: var_presentation,
            rows: var_rows,
            code_text: var_codeText,
            source: var_source,
        };
    }
}

impl SseDecode for crate::api::epub::ReaderBlockKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::ReaderBlockKind::Paragraph,
            1 => crate::api::epub::ReaderBlockKind::Heading,
            2 => crate::api::epub::ReaderBlockKind::BlockQuote,
            3 => crate::api::epub::ReaderBlockKind::List,
            4 => crate::api::epub::ReaderBlockKind::ListItem,
            5 => crate::api::epub::ReaderBlockKind::Image,
            6 => crate::api::epub::ReaderBlockKind::Table,
            7 => crate::api::epub::ReaderBlockKind::HorizontalRule,
            8 => crate::api::epub::ReaderBlockKind::Code,
            _ => unreachable!("Invalid variant for ReaderBlockKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::epub::ReaderDocument {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_chapterHref = <String>::sse_decode(deserializer);
        let mut var_blocks = <Vec<crate::api::epub::ReaderBlock>>::sse_decode(deserializer);
        return crate::api::epub::ReaderDocument {
            chapter_href: var_chapterHref,
            blocks: var_blocks,
        };
    }
}

impl SseDecode for crate::api::epub::ReaderInline {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <crate::api::epub::ReaderInlineKind>::sse_decode(deserializer);
        let mut var_text = <Option<String>>::sse_decode(deserializer);
        let mut var_target = <Option<crate::api::epub::LinkTarget>>::sse_decode(deserializer);
        let mut var_resource = <Option<crate::api::epub::ResourceRef>>::sse_decode(deserializer);
        let mut var_alt = <Option<String>>::sse_decode(deserializer);
        let mut var_presentation =
            <Option<crate::api::epub::ImagePresentation>>::sse_decode(deserializer);
        let mut var_styleHints = <Vec<crate::api::epub::SpanStyleHint>>::sse_decode(deserializer);
        let mut var_children = <Vec<crate::api::epub::ReaderInline>>::sse_decode(deserializer);
        let mut var_source = <crate::api::epub::SourceMap>::sse_decode(deserializer);
        return crate::api::epub::ReaderInline {
            kind: var_kind,
            text: var_text,
            target: var_target,
            resource: var_resource,
            alt: var_alt,
            presentation: var_presentation,
            style_hints: var_styleHints,
            children: var_children,
            source: var_source,
        };
    }
}

impl SseDecode for crate::api::epub::ReaderInlineKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::ReaderInlineKind::Text,
            1 => crate::api::epub::ReaderInlineKind::Span,
            2 => crate::api::epub::ReaderInlineKind::Link,
            3 => crate::api::epub::ReaderInlineKind::Image,
            4 => crate::api::epub::ReaderInlineKind::LineBreak,
            _ => unreachable!("Invalid variant for ReaderInlineKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::epub::ResourceKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::ResourceKind::Image,
            1 => crate::api::epub::ResourceKind::Stylesheet,
            2 => crate::api::epub::ResourceKind::Cover,
            3 => crate::api::epub::ResourceKind::Other,
            _ => unreachable!("Invalid variant for ResourceKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::epub::ResourceRef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_href = <String>::sse_decode(deserializer);
        let mut var_mediaType = <Option<String>>::sse_decode(deserializer);
        let mut var_kind = <crate::api::epub::ResourceKind>::sse_decode(deserializer);
        return crate::api::epub::ResourceRef {
            href: var_href,
            media_type: var_mediaType,
            kind: var_kind,
        };
    }
}

impl SseDecode for crate::api::epub::Section {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_startHref = <String>::sse_decode(deserializer);
        let mut var_startFragment = <Option<String>>::sse_decode(deserializer);
        let mut var_endHref = <Option<String>>::sse_decode(deserializer);
        let mut var_endFragment = <Option<String>>::sse_decode(deserializer);
        let mut var_spineStart = <i32>::sse_decode(deserializer);
        let mut var_spineEnd = <i32>::sse_decode(deserializer);
        let mut var_anchors = <Vec<String>>::sse_decode(deserializer);
        let mut var_document = <crate::api::epub::ReaderDocument>::sse_decode(deserializer);
        return crate::api::epub::Section {
            id: var_id,
            title: var_title,
            start_href: var_startHref,
            start_fragment: var_startFragment,
            end_href: var_endHref,
            end_fragment: var_endFragment,
            spine_start: var_spineStart,
            spine_end: var_spineEnd,
            anchors: var_anchors,
            document: var_document,
        };
    }
}

impl SseDecode for crate::api::epub::SourceMap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_spineIndex = <i32>::sse_decode(deserializer);
        let mut var_href = <String>::sse_decode(deserializer);
        let mut var_fragment = <Option<String>>::sse_decode(deserializer);
        let mut var_nodePath = <Vec<i32>>::sse_decode(deserializer);
        return crate::api::epub::SourceMap {
            spine_index: var_spineIndex,
            href: var_href,
            fragment: var_fragment,
            node_path: var_nodePath,
        };
    }
}

impl SseDecode for crate::api::epub::SpanStyleHint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::epub::SpanStyleHint::Italic,
            1 => crate::api::epub::SpanStyleHint::Bold,
            2 => crate::api::epub::SpanStyleHint::Underline,
            3 => crate::api::epub::SpanStyleHint::Superscript,
            4 => crate::api::epub::SpanStyleHint::Subscript,
            5 => crate::api::epub::SpanStyleHint::Code,
            _ => unreachable!("Invalid variant for SpanStyleHint: {}", inner),
        };
    }
}

impl SseDecode for crate::api::epub::TableCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isHeader = <bool>::sse_decode(deserializer);
        let mut var_inlines = <Vec<crate::api::epub::ReaderInline>>::sse_decode(deserializer);
        let mut var_source = <crate::api::epub::SourceMap>::sse_decode(deserializer);
        return crate::api::epub::TableCell {
            is_header: var_isHeader,
            inlines: var_inlines,
            source: var_source,
        };
    }
}

impl SseDecode for crate::api::epub::TableRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cells = <Vec<crate::api::epub::TableCell>>::sse_decode(deserializer);
        let mut var_source = <crate::api::epub::SourceMap>::sse_decode(deserializer);
        return crate::api::epub::TableRow {
            cells: var_cells,
            source: var_source,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        2 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__epub__init_epub_api_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__epub__open_epub_impl(port, ptr, rust_vec_len, data_len),
        5 => {
            wire__crate__api__epub__read_book_resource_bytes_impl(port, ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::EpubError {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [self.message.into_into_dart().into_dart()].into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::EpubError {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::EpubError>
    for crate::api::epub::EpubError
{
    fn into_into_dart(self) -> crate::api::epub::EpubError {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::EpubMetadata {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.title.into_into_dart().into_dart(),
            self.creator.into_into_dart().into_dart(),
            self.language.into_into_dart().into_dart(),
            self.identifier.into_into_dart().into_dart(),
            self.publisher.into_into_dart().into_dart(),
            self.description.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::EpubMetadata
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::EpubMetadata>
    for crate::api::epub::EpubMetadata
{
    fn into_into_dart(self) -> crate::api::epub::EpubMetadata {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ImageLength {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.value_milli.into_into_dart().into_dart(),
            self.unit.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::ImageLength {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ImageLength>
    for crate::api::epub::ImageLength
{
    fn into_into_dart(self) -> crate::api::epub::ImageLength {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ImageLengthUnit {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Percent => 0.into_dart(),
            Self::Px => 1.into_dart(),
            Self::Em => 2.into_dart(),
            Self::Rem => 3.into_dart(),
            Self::Auto => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ImageLengthUnit
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ImageLengthUnit>
    for crate::api::epub::ImageLengthUnit
{
    fn into_into_dart(self) -> crate::api::epub::ImageLengthUnit {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ImagePresentation {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.max_width.into_into_dart().into_dart(),
            self.max_height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ImagePresentation
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ImagePresentation>
    for crate::api::epub::ImagePresentation
{
    fn into_into_dart(self) -> crate::api::epub::ImagePresentation {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::LinkTarget {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.href.into_into_dart().into_dart(),
            self.section_id.into_into_dart().into_dart(),
            self.section_index.into_into_dart().into_dart(),
            self.fragment.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::LinkTarget {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::LinkTarget>
    for crate::api::epub::LinkTarget
{
    fn into_into_dart(self) -> crate::api::epub::LinkTarget {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::LinkTargetKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Internal => 0.into_dart(),
            Self::External => 1.into_dart(),
            Self::Unresolved => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::LinkTargetKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::LinkTargetKind>
    for crate::api::epub::LinkTargetKind
{
    fn into_into_dart(self) -> crate::api::epub::LinkTargetKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ListItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.blocks.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::ListItem {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ListItem> for crate::api::epub::ListItem {
    fn into_into_dart(self) -> crate::api::epub::ListItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ParsedEpubBook {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.metadata.into_into_dart().into_dart(),
            self.cover_image.into_into_dart().into_dart(),
            self.sections.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ParsedEpubBook
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ParsedEpubBook>
    for crate::api::epub::ParsedEpubBook
{
    fn into_into_dart(self) -> crate::api::epub::ParsedEpubBook {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ReaderBlock {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.level.into_into_dart().into_dart(),
            self.ordered.into_into_dart().into_dart(),
            self.inlines.into_into_dart().into_dart(),
            self.blocks.into_into_dart().into_dart(),
            self.items.into_into_dart().into_dart(),
            self.resource.into_into_dart().into_dart(),
            self.alt.into_into_dart().into_dart(),
            self.caption.into_into_dart().into_dart(),
            self.presentation.into_into_dart().into_dart(),
            self.rows.into_into_dart().into_dart(),
            self.code_text.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::ReaderBlock {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ReaderBlock>
    for crate::api::epub::ReaderBlock
{
    fn into_into_dart(self) -> crate::api::epub::ReaderBlock {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ReaderBlockKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Paragraph => 0.into_dart(),
            Self::Heading => 1.into_dart(),
            Self::BlockQuote => 2.into_dart(),
            Self::List => 3.into_dart(),
            Self::ListItem => 4.into_dart(),
            Self::Image => 5.into_dart(),
            Self::Table => 6.into_dart(),
            Self::HorizontalRule => 7.into_dart(),
            Self::Code => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ReaderBlockKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ReaderBlockKind>
    for crate::api::epub::ReaderBlockKind
{
    fn into_into_dart(self) -> crate::api::epub::ReaderBlockKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ReaderDocument {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.chapter_href.into_into_dart().into_dart(),
            self.blocks.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ReaderDocument
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ReaderDocument>
    for crate::api::epub::ReaderDocument
{
    fn into_into_dart(self) -> crate::api::epub::ReaderDocument {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ReaderInline {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.text.into_into_dart().into_dart(),
            self.target.into_into_dart().into_dart(),
            self.resource.into_into_dart().into_dart(),
            self.alt.into_into_dart().into_dart(),
            self.presentation.into_into_dart().into_dart(),
            self.style_hints.into_into_dart().into_dart(),
            self.children.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ReaderInline
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ReaderInline>
    for crate::api::epub::ReaderInline
{
    fn into_into_dart(self) -> crate::api::epub::ReaderInline {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ReaderInlineKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Text => 0.into_dart(),
            Self::Span => 1.into_dart(),
            Self::Link => 2.into_dart(),
            Self::Image => 3.into_dart(),
            Self::LineBreak => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ReaderInlineKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ReaderInlineKind>
    for crate::api::epub::ReaderInlineKind
{
    fn into_into_dart(self) -> crate::api::epub::ReaderInlineKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ResourceKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Image => 0.into_dart(),
            Self::Stylesheet => 1.into_dart(),
            Self::Cover => 2.into_dart(),
            Self::Other => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::ResourceKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ResourceKind>
    for crate::api::epub::ResourceKind
{
    fn into_into_dart(self) -> crate::api::epub::ResourceKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::ResourceRef {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.href.into_into_dart().into_dart(),
            self.media_type.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::ResourceRef {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::ResourceRef>
    for crate::api::epub::ResourceRef
{
    fn into_into_dart(self) -> crate::api::epub::ResourceRef {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::Section {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.start_href.into_into_dart().into_dart(),
            self.start_fragment.into_into_dart().into_dart(),
            self.end_href.into_into_dart().into_dart(),
            self.end_fragment.into_into_dart().into_dart(),
            self.spine_start.into_into_dart().into_dart(),
            self.spine_end.into_into_dart().into_dart(),
            self.anchors.into_into_dart().into_dart(),
            self.document.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::Section {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::Section> for crate::api::epub::Section {
    fn into_into_dart(self) -> crate::api::epub::Section {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::SourceMap {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.spine_index.into_into_dart().into_dart(),
            self.href.into_into_dart().into_dart(),
            self.fragment.into_into_dart().into_dart(),
            self.node_path.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::SourceMap {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::SourceMap>
    for crate::api::epub::SourceMap
{
    fn into_into_dart(self) -> crate::api::epub::SourceMap {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::SpanStyleHint {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Italic => 0.into_dart(),
            Self::Bold => 1.into_dart(),
            Self::Underline => 2.into_dart(),
            Self::Superscript => 3.into_dart(),
            Self::Subscript => 4.into_dart(),
            Self::Code => 5.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::epub::SpanStyleHint
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::SpanStyleHint>
    for crate::api::epub::SpanStyleHint
{
    fn into_into_dart(self) -> crate::api::epub::SpanStyleHint {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::TableCell {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_header.into_into_dart().into_dart(),
            self.inlines.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::TableCell {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::TableCell>
    for crate::api::epub::TableCell
{
    fn into_into_dart(self) -> crate::api::epub::TableCell {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::epub::TableRow {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cells.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::epub::TableRow {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::epub::TableRow> for crate::api::epub::TableRow {
    fn into_into_dart(self) -> crate::api::epub::TableRow {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::epub::EpubError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for crate::api::epub::EpubMetadata {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.creator, serializer);
        <Option<String>>::sse_encode(self.language, serializer);
        <Option<String>>::sse_encode(self.identifier, serializer);
        <Option<String>>::sse_encode(self.publisher, serializer);
        <Option<String>>::sse_encode(self.description, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::epub::ImageLength {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.value_milli, serializer);
        <crate::api::epub::ImageLengthUnit>::sse_encode(self.unit, serializer);
    }
}

impl SseEncode for crate::api::epub::ImageLengthUnit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::ImageLengthUnit::Percent => 0,
                crate::api::epub::ImageLengthUnit::Px => 1,
                crate::api::epub::ImageLengthUnit::Em => 2,
                crate::api::epub::ImageLengthUnit::Rem => 3,
                crate::api::epub::ImageLengthUnit::Auto => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::epub::ImagePresentation {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::epub::ImageLength>>::sse_encode(self.width, serializer);
        <Option<crate::api::epub::ImageLength>>::sse_encode(self.height, serializer);
        <Option<crate::api::epub::ImageLength>>::sse_encode(self.max_width, serializer);
        <Option<crate::api::epub::ImageLength>>::sse_encode(self.max_height, serializer);
    }
}

impl SseEncode for crate::api::epub::LinkTarget {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::epub::LinkTargetKind>::sse_encode(self.kind, serializer);
        <String>::sse_encode(self.href, serializer);
        <Option<String>>::sse_encode(self.section_id, serializer);
        <Option<i32>>::sse_encode(self.section_index, serializer);
        <Option<String>>::sse_encode(self.fragment, serializer);
    }
}

impl SseEncode for crate::api::epub::LinkTargetKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::LinkTargetKind::Internal => 0,
                crate::api::epub::LinkTargetKind::External => 1,
                crate::api::epub::LinkTargetKind::Unresolved => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::epub::ListItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::epub::ReaderBlock>>::sse_encode(self.blocks, serializer);
        <crate::api::epub::SourceMap>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for Vec<crate::api::epub::ListItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::ListItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <i32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::ReaderBlock> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::ReaderBlock>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::ReaderInline> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::ReaderInline>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::Section> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::Section>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::SpanStyleHint> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::SpanStyleHint>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::TableCell> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::TableCell>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::epub::TableRow> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::epub::TableRow>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::epub::ImageLength> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::epub::ImageLength>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::epub::ImagePresentation> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::epub::ImagePresentation>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::epub::LinkTarget> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::epub::LinkTarget>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::epub::ResourceRef> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::epub::ResourceRef>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::epub::ParsedEpubBook {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::epub::EpubMetadata>::sse_encode(self.metadata, serializer);
        <Option<Vec<u8>>>::sse_encode(self.cover_image, serializer);
        <Vec<crate::api::epub::Section>>::sse_encode(self.sections, serializer);
    }
}

impl SseEncode for crate::api::epub::ReaderBlock {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::epub::ReaderBlockKind>::sse_encode(self.kind, serializer);
        <i32>::sse_encode(self.level, serializer);
        <bool>::sse_encode(self.ordered, serializer);
        <Vec<crate::api::epub::ReaderInline>>::sse_encode(self.inlines, serializer);
        <Vec<crate::api::epub::ReaderBlock>>::sse_encode(self.blocks, serializer);
        <Vec<crate::api::epub::ListItem>>::sse_encode(self.items, serializer);
        <Option<crate::api::epub::ResourceRef>>::sse_encode(self.resource, serializer);
        <Option<String>>::sse_encode(self.alt, serializer);
        <Option<String>>::sse_encode(self.caption, serializer);
        <Option<crate::api::epub::ImagePresentation>>::sse_encode(self.presentation, serializer);
        <Vec<crate::api::epub::TableRow>>::sse_encode(self.rows, serializer);
        <Option<String>>::sse_encode(self.code_text, serializer);
        <crate::api::epub::SourceMap>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for crate::api::epub::ReaderBlockKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::ReaderBlockKind::Paragraph => 0,
                crate::api::epub::ReaderBlockKind::Heading => 1,
                crate::api::epub::ReaderBlockKind::BlockQuote => 2,
                crate::api::epub::ReaderBlockKind::List => 3,
                crate::api::epub::ReaderBlockKind::ListItem => 4,
                crate::api::epub::ReaderBlockKind::Image => 5,
                crate::api::epub::ReaderBlockKind::Table => 6,
                crate::api::epub::ReaderBlockKind::HorizontalRule => 7,
                crate::api::epub::ReaderBlockKind::Code => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::epub::ReaderDocument {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.chapter_href, serializer);
        <Vec<crate::api::epub::ReaderBlock>>::sse_encode(self.blocks, serializer);
    }
}

impl SseEncode for crate::api::epub::ReaderInline {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::epub::ReaderInlineKind>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.text, serializer);
        <Option<crate::api::epub::LinkTarget>>::sse_encode(self.target, serializer);
        <Option<crate::api::epub::ResourceRef>>::sse_encode(self.resource, serializer);
        <Option<String>>::sse_encode(self.alt, serializer);
        <Option<crate::api::epub::ImagePresentation>>::sse_encode(self.presentation, serializer);
        <Vec<crate::api::epub::SpanStyleHint>>::sse_encode(self.style_hints, serializer);
        <Vec<crate::api::epub::ReaderInline>>::sse_encode(self.children, serializer);
        <crate::api::epub::SourceMap>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for crate::api::epub::ReaderInlineKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::ReaderInlineKind::Text => 0,
                crate::api::epub::ReaderInlineKind::Span => 1,
                crate::api::epub::ReaderInlineKind::Link => 2,
                crate::api::epub::ReaderInlineKind::Image => 3,
                crate::api::epub::ReaderInlineKind::LineBreak => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::epub::ResourceKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::ResourceKind::Image => 0,
                crate::api::epub::ResourceKind::Stylesheet => 1,
                crate::api::epub::ResourceKind::Cover => 2,
                crate::api::epub::ResourceKind::Other => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::epub::ResourceRef {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.href, serializer);
        <Option<String>>::sse_encode(self.media_type, serializer);
        <crate::api::epub::ResourceKind>::sse_encode(self.kind, serializer);
    }
}

impl SseEncode for crate::api::epub::Section {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.title, serializer);
        <String>::sse_encode(self.start_href, serializer);
        <Option<String>>::sse_encode(self.start_fragment, serializer);
        <Option<String>>::sse_encode(self.end_href, serializer);
        <Option<String>>::sse_encode(self.end_fragment, serializer);
        <i32>::sse_encode(self.spine_start, serializer);
        <i32>::sse_encode(self.spine_end, serializer);
        <Vec<String>>::sse_encode(self.anchors, serializer);
        <crate::api::epub::ReaderDocument>::sse_encode(self.document, serializer);
    }
}

impl SseEncode for crate::api::epub::SourceMap {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.spine_index, serializer);
        <String>::sse_encode(self.href, serializer);
        <Option<String>>::sse_encode(self.fragment, serializer);
        <Vec<i32>>::sse_encode(self.node_path, serializer);
    }
}

impl SseEncode for crate::api::epub::SpanStyleHint {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::epub::SpanStyleHint::Italic => 0,
                crate::api::epub::SpanStyleHint::Bold => 1,
                crate::api::epub::SpanStyleHint::Underline => 2,
                crate::api::epub::SpanStyleHint::Superscript => 3,
                crate::api::epub::SpanStyleHint::Subscript => 4,
                crate::api::epub::SpanStyleHint::Code => 5,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::epub::TableCell {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_header, serializer);
        <Vec<crate::api::epub::ReaderInline>>::sse_encode(self.inlines, serializer);
        <crate::api::epub::SourceMap>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for crate::api::epub::TableRow {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<crate::api::epub::TableCell>>::sse_encode(self.cells, serializer);
        <crate::api::epub::SourceMap>::sse_encode(self.source, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
