// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/book.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4231649898290285961),
    name: 'Book',
    lastPropertyId: const obx_int.IdUid(11, 539036788110333090),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 511664252706428705),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5923442671180129333),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5272004451845463450),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7416197562652689876),
        name: 'language',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9046309080833990580),
        name: 'publisher',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1525244759724470983),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2036148119583082127),
        name: 'coverImage',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 922965206974107145),
        name: 'chapterCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4542581854366576531),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7114892809769883659),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 539036788110333090),
        name: 'progress',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4231649898290285961),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Book: obx_int.EntityDefinition<Book>(
      model: _entities[0],
      toOneRelations: (Book object) => [],
      toManyRelations: (Book object) => {},
      getId: (Book object) => object.id,
      setId: (Book object, int id) {
        object.id = id;
      },
      objectToFB: (Book object, fb.Builder fbb) {
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final authorOffset = object.author == null
            ? null
            : fbb.writeString(object.author!);
        final languageOffset = object.language == null
            ? null
            : fbb.writeString(object.language!);
        final publisherOffset = object.publisher == null
            ? null
            : fbb.writeString(object.publisher!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final coverImageOffset = object.coverImage == null
            ? null
            : fbb.writeListInt8(object.coverImage!);
        final filePathOffset = fbb.writeString(object.filePath);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, authorOffset);
        fbb.addOffset(3, languageOffset);
        fbb.addOffset(4, publisherOffset);
        fbb.addOffset(5, descriptionOffset);
        fbb.addOffset(6, coverImageOffset);
        fbb.addInt64(7, object.chapterCount);
        fbb.addOffset(8, filePathOffset);
        fbb.addInt64(9, object.addedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.progress);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final languageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final publisherParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final coverImageParam =
            const fb.Uint8ListReader(
                  lazy: false,
                ).vTableGetNullable(buffer, rootOffset, 16)
                as Uint8List?;
        final chapterCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final progressParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = Book(
          id: idParam,
          title: titleParam,
          author: authorParam,
          language: languageParam,
          publisher: publisherParam,
          description: descriptionParam,
          coverImage: coverImageParam,
          chapterCount: chapterCountParam,
          filePath: filePathParam,
          addedAt: addedAtParam,
          progress: progressParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// See [Book.id].
  static final id = obx.QueryIntegerProperty<Book>(_entities[0].properties[0]);

  /// See [Book.title].
  static final title = obx.QueryStringProperty<Book>(
    _entities[0].properties[1],
  );

  /// See [Book.author].
  static final author = obx.QueryStringProperty<Book>(
    _entities[0].properties[2],
  );

  /// See [Book.language].
  static final language = obx.QueryStringProperty<Book>(
    _entities[0].properties[3],
  );

  /// See [Book.publisher].
  static final publisher = obx.QueryStringProperty<Book>(
    _entities[0].properties[4],
  );

  /// See [Book.description].
  static final description = obx.QueryStringProperty<Book>(
    _entities[0].properties[5],
  );

  /// See [Book.coverImage].
  static final coverImage = obx.QueryByteVectorProperty<Book>(
    _entities[0].properties[6],
  );

  /// See [Book.chapterCount].
  static final chapterCount = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[7],
  );

  /// See [Book.filePath].
  static final filePath = obx.QueryStringProperty<Book>(
    _entities[0].properties[8],
  );

  /// See [Book.addedAt].
  static final addedAt = obx.QueryDateProperty<Book>(
    _entities[0].properties[9],
  );

  /// See [Book.progress].
  static final progress = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[10],
  );
}
